### ISSUE TITLE
Priorities

### ISSUE THREAD

**Issue by prologic** [openmicroapps/meta#13]
Let's stick to two very simple priorities:

- Must Have
- Nice to Have

?

**Comment by jtagcat** [comment]
Must have - Urgent?

**Comment by prologic** [comment]
That's kind of what I'm thinking. Keep it simple at just two. Must have and Nice to have.
The problem I find with priorities  more than this is things start to get muddled and then you have no idea in what order to do anything in because everything is either urgent or hi-pri :)

**Comment by jtagcat** [comment]
So.. see the labels:
p-1=future
p1=first priority
p2=nice to have

**Comment by prologic** [comment]
Yeap I like this :) -- And Future means "Must have" but "We'll do it next/later"?

**Comment by jtagcat** [comment]
You can see [future](https://en.wikipedia.org/wiki/Future) for an answer to that.
