### ISSUE TITLE
Interest in packaging/intent to package for Sandstorm

### ISSUE THREAD

**Issue by ocdtrekkie** [openmicroapps/meta#14]
This is possibly related to #4 in particular.

I found your todo app, and immediately noticed "hey, this probably would package _very_ cleanly for Sandstorm". Then I noticed you have _other apps_ that are likely easy to package for Sandstorm for the same reason. (Chiefly, that there isn't an account model we have to rip out or bypass, and that it's extremely easy to relocate the data storage to /var.)

Sandstorm.io provides the overarching account/sharing/security model for applications written... essentially the way OpenMicroApps are written. So I figured I'd mention I am kinda interested in trying to package a couple to see how it goes. The followup question would be, if I create Sandstorm packages, would you be interested in me upstreaming the related files (they live in a .sandstorm folder in the repo, not dissimilar from .github)?

**Comment by ocdtrekkie** [comment]
It's kinda interesting to read some of the meta posts because a lot of the goals of this project are identical to Sandstorm's. It's intriguing that the most recent issue talks about defined Protobufs presumably for apps talking to each other or the platform, as Sandstorm was developed by the author of Protobufs v2 (and it's successor, Cap'n Proto), and uses Cap'n Proto RPCs for all communications in and out of apps and the platform.

Sandstorm itself is not exactly "micro", but it's grain model effectively only works well if it's apps are micro, since each "document" is an entire instance of an app run-on-demand. Apps are best being very limited in scope, and using communication between apps or bundling of apps to manage more complex tasks and projects.

Hilariously, even the style requirements look very close: Purple, as I noticed in some of the apps, is pretty much the Sandstorm color of choice, and the squared-off style is very similar to Sandstorm's UI style as well.

**Comment by prologic** [comment]
As mentioned  prologic/todo#31 this org sort of went nowhere sadly. It was a good idea at the time but fizzled out. Please feel free to build Sandstorm "gains"? for any of the following my self-hosted apps you see [here](https://gist.github.com/prologic/c165403fb6ac07c16dc9fd6eeb8efbd2) :)
