### ISSUE TITLE
Find a way for general chat.

### ISSUE THREAD

**Issue by jtagcat** [openmicroapps/meta#6]
I suggest Matrix.org. Should the public room be hosted on matrix.org or our own homeserver?

**Comment by prologic** [comment]
matrix.org Is probably fine for now?
-- 

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by jtagcat** [comment]
https://matrix.to/#/#openmicroapps:matrix.org

**Comment by jtagcat** [comment]
@prologic 
![image](https://user-images.githubusercontent.com/38327267/62003651-b752f500-b109-11e9-9c57-0f1ac779b9c5.png)

**Comment by prologic** [comment]
<img width="772" alt="Screen Shot 2019-07-28 at 5 50 50 PM" src="https://user-images.githubusercontent.com/1290234/62003833-54407d00-b160-11e9-81aa-35aea8876678.png">

**Comment by jtagcat** [comment]
Sorry try again, I published the room on the index, but forgot you need to also make people able to join.
